# Workflow that runs the 'pytest' and 'flake8' command on every push to master
name: Pytest Workflow

on:
  push:
    branches:
      - master

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r starter/requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Pull data from DVC
        run: dvc pull data -R

      - name: Run Flake8
        run: flake8

      - name: Run Pytest
        run: pytest